### ISSUE TITLE
snmp checks

### ISSUE THREAD

**Issue by csmith** [csmith/goplum#26]

**Comment by tsumaru720** [comment]
should probably support some of the more we'll known OIDs by default such as what snmpd exposes for disk usage, load average, memory usage etc for linux / windows

Also should support the user being able to provide an arbitrary OID to use also

**Comment by csmith** [comment]
Open question: what would the failure criteria actually be? Limit it to numeric fields and have `at_least` and `at_most` parameters?

**Comment by tsumaru720** [comment]
SNMP can also return strings, so I think similar options to what the http.get plugin has, in addition to being able to handle numbers. If its outside of those range/doesnt meet that criteria (or times out)
