### ISSUE TITLE
Quieter logging

### ISSUE THREAD

**Issue by tsumaru720** [csmith/goplum#29]
Could be good to have an option to suppress some of the log output

for example, only show checks that change the fall/recover counters + alerts - rather than every check

**Comment by csmith** [comment]
Probably won't be an option, but will get rid of the check output at some point once that code is stable and working well

**Comment by csmith** [comment]
I've done a complete 180 on my thinking and added a flag.

**Comment by csmith** [comment]
09c3b4f25a469f6075df692d021e6c87e583e595
