### ISSUE TITLE
Heartbeat monitoring

### ISSUE THREAD

**Issue by csmith** [csmith/goplum#32]
Some kind of check that expects a remotely-provided heartbeat at a certain interval

e.g. monitoring of daily cron jobs - they report success when they finish and the check fails if it hasn't received such a report in the last N hours.

**Comment by ShaneMcC** [comment]
My thoughts on this:

- By default, it should just accept a GET to some kind of unique string (eg https://goplum:4567/heartbeat/some-unique-string-here) for maximum compatibility.  (Ie, don't make it (just) a gRPC call or something excessive like that!)
    - This string should probably be user-generated, to ensure someone can easily know what it should be.
    - The check-name is probably not a good idea in general, you don't want someone to guess at your thing.
    - This should count as a success

- Ideally going beyond the MVP implementation, also accept POST data (json? form-encoded? Don't really care) (or GET Params) to provide some extra data (eg `status=<ok|warn|error>&message=something+broke`
    - eg maybe I want to poke it to let it know there was a failure rather than just not poking it, and then maybe also provide the "status" text or so.

**Comment by csmith** [comment]
Yep, that's roughly what I was thinking. Probably go for GET params for status/details/etc.

I'll probably make the key configurable but force it to be something like 32-char alphanumeric to avoid stupid.

This all depends on #33 as the plugin will need to be configured as to what port/path it listens on
