### ISSUE TITLE
Run executables/scripts to get check status

### ISSUE THREAD

**Issue by ShaneMcC** [csmith/goplum#9]
Sometimes it may not be feasible to write a plugin module for a one-off check. It would be nice to be able to run an external script/executable and read the return code (0/1/2 for success/fail/warning ?).

Possibly capture the last line of the output or so for the "detail" message.

**Comment by csmith** [comment]
I'm not super keen on this - it feels it leads to the quagmire of Nagios-style monitoring where you're just running random executables and scripts with poorly documented arguments, their own sets of dependencies, etc.

Do you have an example of what a "one-off check" would look like?

**Comment by ShaneMcC** [comment]
I have some fairly use-case-specific checks I'd use for mydnshost that wouldn't make sense to be implemented by you, and I don't write go so writing a plugin in go is extreme compared to "did the shell script exit with 0?". Also potentially depending on how you're using it/where you're running it you might want to monitor the result of `systemctl status <app>` or so.

**Comment by csmith** [comment]
I see.

For things like mydnshost it feels that it'd be nicer if mydnshost had an endpoint that did all these specific checks and returned a result (in a nice standard way: https://inadarei.github.io/rfc-healthcheck/). Then the result can be monitored nicely without the monitoring system having to know all the intricate details of what makes that particular app tick.

(And by "feel" I mean "In my mental model of how the world should work, which is possibly completely unrealistic and probably completely different to yours/everyone else's")
